use_gpu: True
device: 0
seed: 0
early_stop:
  patience: 10
  improve_indicator_mode: best
  the_smaller_the_better: False
federate:
  mode: standalone
  method: local
  make_global_eval: False
  total_round_num: 200
  share_local_model: False
  client_num: 13
  clients_id: []
data:
  batch_size: 64
  root: data/
  type: cikmcup
model:
  type: gin
  hidden: 64
  task: graph
  out_channels: 2
personalization:
  local_param: ['encoder_atom', 'encoder', 'clf']
train:
  batch_or_epoch: epoch
  local_update_steps: 1
  optimizer:
    weight_decay: 0.0005
    type: SGD
    momentum: 0.9
trainer:
  type: graphminibatch_trainer
eval:
  freq: 1
  report: ['avg']
  best_res_update_round_wise_key: val_imp_ratio
  count_flops: False
  split: ['val']

